# Generated by Django 3.1.2 on 2020-10-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_surface_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='average_request_time',
            field=models.FloatField(default=0),
        ),
    ]
